// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiTTP3Su9RsQXZb4gu_3uB4tezvSHh8q0',
    appId: '1:860886752746:web:ac43412416b66f636be693',
    messagingSenderId: '860886752746',
    projectId: 'fdasf-41c94',
    authDomain: 'fdasf-41c94.firebaseapp.com',
    storageBucket: 'fdasf-41c94.firebasestorage.app',
    measurementId: 'G-RSMBCG47GT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA28qrU_HPbnccs9klZX9l0l7yF-jXz3MQ',
    appId: '1:860886752746:android:ff8b3928f7f88cea6be693',
    messagingSenderId: '860886752746',
    projectId: 'fdasf-41c94',
    storageBucket: 'fdasf-41c94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxeBATgrGTt0L-ORYDyO2qe_b2YrGNCLs',
    appId: '1:860886752746:ios:bed3e517c93afc7f6be693',
    messagingSenderId: '860886752746',
    projectId: 'fdasf-41c94',
    storageBucket: 'fdasf-41c94.firebasestorage.app',
    iosBundleId: 'com.example.happyfood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxeBATgrGTt0L-ORYDyO2qe_b2YrGNCLs',
    appId: '1:860886752746:ios:bed3e517c93afc7f6be693',
    messagingSenderId: '860886752746',
    projectId: 'fdasf-41c94',
    storageBucket: 'fdasf-41c94.firebasestorage.app',
    iosBundleId: 'com.example.happyfood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuq3A9Kvb5M0MhfT9poK_1NerWE5oiy8U',
    appId: '1:860886752746:web:6c9a4f388e5a2a256be693',
    messagingSenderId: '860886752746',
    projectId: 'fdasf-41c94',
    authDomain: 'fdasf-41c94.firebaseapp.com',
    storageBucket: 'fdasf-41c94.firebasestorage.app',
    measurementId: 'G-0PHXC8M0T0',
  );
}
